----------------------------------------
TEST MODULE FOR 7-base_geometry.py
----------------------------------------

Usage: bg = BaseGeometry()

::

    >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

Test 1: basic test

::

    >>> bg = BaseGeometry()
    >>> bg.integer_validator("my_int", 12)
    >>> bg.integer_validator("width", 89)
    >>> bg.integer_validator("name", "5")
    Traceback (most recent call last):
    TypeError: name must be an integer


    >>> bg.integer_validator("name", "John")
    Traceback (most recent call last):
    TypeError: name must be an integer

    >>> bg.integer_validator("age", 0)
    Traceback (most recent call last):
    ValueError: age must be greater than 0

    >>> bg.integer_validator("distance", -4)
    Traceback (most recent call last):
    ValueError: distance must be greater than 0

Test suites 2:

::

    >>> bg.integer_validator("data", [-4, 5, 3])
    Traceback (most recent call last):
    TypeError: data must be an integer


    >>> bg.integer_validator("data", None)
    Traceback (most recent call last):
    TypeError: data must be an integer


    >>> bg.integer_validator("data",)
    Traceback (most recent call last):
    TypeError: BaseGeometry.integer_validator() missing 1 required positional argument: 'value'

    >>> bg.integer_validator()
    Traceback (most recent call last):
    TypeError: BaseGeometry.integer_validator() missing 2 required positional arguments: 'name' and 'value'

Test suite 3:

::


    >>> bg.area()
    Traceback (most recent call last):
    Exception: area() is not implemented


    >>> bg = BaseGeometry()
    >>> bg.area(7)
    Traceback (most recent call last):
    TypeError: BaseGeometry.area() takes 1 positional argument but 2 were given


Test suites 4:

:: 


    >>> bg.integer_validator("data", 1, 20)
    Traceback (most recent call last):
    TypeError: BaseGeometry.integer_validator() takes 3 positional arguments but 4 were given

    >>> bg = BaseGeometry()
    >>> bg.integer_validator("age", {3, 4})
    Traceback (most recent call last):
    TypeError: age must be an integer


    >>> bg.integer_validator("bool", false)
    Traceback (most recent call last):
    NameError: name 'false' is not defined


    >>> bg.integer_validator("bool", False)
    Traceback (most recent call last):
    TypeError: bool must be an integer
